#!/usr/bin/env node
/**
 * Evidence-log contract — a reading that a document cites must say how to take it again.
 *
 * WHY THIS EXISTS
 * ---------------
 * `docs/probe-*.log` are the measurements this repository argues from: `recovery.md` §1 shows the
 * orphan lines from `probe-m3-restart.log`, §9 shows the full-volume lines from `probe-disk-full.log`,
 * `install.md` shows what `dsh plugin --add` did. They are the only kind of document here that cannot
 * be regenerated by a suite — they need a real kill, a real full disk, a real 1080p render — so the
 * ONE thing they must carry is the way back to the measurement.
 *
 * MEASURED, round 32: one of them did not, and the tool behind it had rotted. `probe-m3-restart.log`
 * was cited for twelve rounds while `m3-restart-probe.mjs` died with
 *
 *   ENOENT … /revisions/r0029/scene-spec.json
 *
 * because it defaulted to a revision the demo project had moved past. Nobody could tell from the log,
 * because the log did not say what command produced it. That is the defect this file makes impossible:
 *
 *   - every log opens with a `#` title and carries, in its leading block, a DATE and a COMMAND;
 *   - the command must exist — the rule `contributor-surface.test.mjs` applies to the templates, from
 *     the same module (`tests/lib/command-claims.mjs`), so a renamed script is caught here too;
 *   - every log must be CITED by a document. An evidence file nothing points at is dead weight, and
 *     the reverse direction matters as much: a document that cites a log which no longer exists.
 *
 * Run: node deepblend/tests/contract/probe-logs.test.mjs
 *
 * Owner: DeepBlend Studio — M5
 */

import { test } from 'node:test'
import assert from 'node:assert/strict'
import { existsSync, readFileSync, readdirSync } from 'node:fs'
import { basename, join } from 'node:path'

import { missingCommands } from '../lib/command-claims.mjs'
import { ROOT } from '../../tools/workspace-layout.mjs'

const DOCS = join(ROOT, 'deepblend', 'docs')
const logs = readdirSync(DOCS).filter(name => /^probe-.*\.log$/.test(name)).sort()
const packageJson = JSON.parse(readFileSync(join(ROOT, 'package.json'), 'utf8'))

/** Every document that could cite a log, as `{name, text}`. */
const documents = [
  ['README.md', readFileSync(join(ROOT, 'README.md'), 'utf8')],
  ...readdirSync(DOCS)
    .filter(name => name.endsWith('.md'))
    .map(name => [name, readFileSync(join(DOCS, name), 'utf8')]),
]

/**
 * The header of a log: the run of lines at the top that are marked as header — `#` comments, and `>`
 * quotes for the one log written in that style.
 *
 * MEASURED reason this is not "everything before the first blank line": the first version of this
 * checker used that, and it read straight through into the body of `probe-disk-full.log`, whose own
 * output begins with a `date:` line. Deleting every date from that file's HEADER still passed the date
 * rule — the body was supplying one — which is the same shape of mistake as a check that cannot fail.
 */
const headerOf = text => {
  const lines = []
  for (const line of text.split('\n')) {
    if (line.startsWith('#') || line.startsWith('>')) lines.push(line)
    else break
  }
  return lines.join('\n')
}

/**
 * The faults in one log's header, as human-readable strings (empty means reproducible).
 *
 * Exported through the test below rather than kept private: a rule whose checker cannot be shown to
 * fail is a rule nobody has checked, and the negative controls at the end of this file drive this
 * function on logs that are broken in each documented way.
 *
 * @param {{name: string, text: string, scripts: Record<string, string>, root: string, citedBy: string[]}} input
 * @returns {string[]}
 */
export function logFaults(input) {
  const faults = []
  const header = headerOf(input.text)
  if (!input.text.startsWith('#')) {
    faults.push('no "#" title on the first line, so it does not read as a curated reading')
  }
  if (!/\d{4}-\d{2}-\d{2}/.test(header)) {
    faults.push('no date (YYYY-MM-DD) in the leading block, so a reader cannot tell how old it is')
  }
  const commands = missingCommands(header, { scripts: input.scripts, root: input.root })
  if (commands.length > 0) {
    faults.push(`names ${commands.join(', ')}, which cannot be run`)
  }
  if (!/(?:node|bash|npm run)\s/.test(header)) {
    faults.push('no command in the leading block, so the reading cannot be taken again')
  }
  if (input.citedBy.length === 0) {
    faults.push('no document cites this log, so nothing would notice if it rotted')
  }
  return faults
}

test('there are evidence logs at all, so this check is not vacuous', () => {
  assert.ok(logs.length >= 5, `only ${logs.length} evidence log(s) found in deepblend/docs`)
})

test('every evidence log says how it was taken, and when', () => {
  for (const name of logs) {
    const citedBy = documents.filter(([, text]) => text.includes(name)).map(([document]) => document)
    const faults = logFaults({
      name,
      text: readFileSync(join(DOCS, name), 'utf8'),
      scripts: packageJson.scripts,
      root: ROOT,
      citedBy,
    })
    assert.deepEqual(faults, [], `${name}: ${faults.join('; ')}`)
  }
})

test('every log a document cites exists', () => {
  // The other direction: a citation to a renamed or deleted log is worse than no citation, because it
  // reads like evidence. This is the same rule `docs-consistency.test.mjs` applies to the manuals'
  // citations, checked here for every document at once.
  const missing = new Set()
  for (const [name, text] of documents) {
    for (const match of text.matchAll(/\bprobe-[\w.-]*\.log\b/g)) {
      if (!existsSync(join(DOCS, match[0]))) missing.add(`${name} -> ${match[0]}`)
    }
  }
  assert.deepEqual([...missing], [])
})

test('the checker names every fault on logs that are wrong in each documented way', () => {
  // Without these, the rule above could be passing because the checker finds nothing at all.
  const context = { scripts: { test: 'node deepblend/tests/run.mjs' }, root: ROOT }
  const good = {
    name: 'probe-example.log',
    text: '# Example probe — what it measured\n#\n#   node deepblend/tests/run.mjs\n#\n# Taken 2026-09-15.\n\nbody\n',
    ...context,
    citedBy: ['README.md'],
  }
  assert.deepEqual(logFaults(good), [], 'a well-formed log must come back clean')

  // A file whose first line is not header has NO header: every rule fails, and that is the point of
  // starting the header at line one rather than looking for a `#` somewhere.
  assert.deepEqual(
    logFaults({ ...good, text: good.text.slice(1) }),
    [
      'no "#" title on the first line, so it does not read as a curated reading',
      'no date (YYYY-MM-DD) in the leading block, so a reader cannot tell how old it is',
      'no command in the leading block, so the reading cannot be taken again',
    ],
  )
  assert.deepEqual(
    logFaults({ ...good, text: '# Example\n#   node deepblend/tests/run.mjs\n\nbody\n' }),
    ['no date (YYYY-MM-DD) in the leading block, so a reader cannot tell how old it is'],
  )
  assert.deepEqual(
    logFaults({ ...good, text: '# Example\n#   2026-09-15\n\nbody\n' }),
    ['no command in the leading block, so the reading cannot be taken again'],
  )
  assert.deepEqual(
    logFaults({ ...good, text: '# Example\n#   node deepblend/tools/gone.mjs\n#   2026-09-15\n\nbody\n' }),
    ['names deepblend/tools/gone.mjs, which cannot be run'],
  )
  assert.deepEqual(
    logFaults({ ...good, citedBy: [] }),
    ['no document cites this log, so nothing would notice if it rotted'],
  )
})

test('the header is the header, not "anywhere near the top of the file"', () => {
  // A date in the body does not tell a reader when the READING is from — and several probes print
  // timestamps of their own, `probe-disk-full.log` on its very first body line. This is the control for
  // the version of this checker that read through into the body and accepted that timestamp.
  const buried = '# Example\n\ndate: 2026-09-15T00:00:00Z\nnode deepblend/tests/run.mjs\n'
  const faults = logFaults({
    name: 'probe-example.log',
    text: buried,
    scripts: { test: 'node deepblend/tests/run.mjs' },
    root: ROOT,
    citedBy: ['README.md'],
  })
  assert.ok(faults.some(fault => fault.startsWith('no date')), `a body date satisfied the header rule: ${faults}`)
  assert.ok(faults.some(fault => fault.startsWith('no command')), `a body command satisfied the header rule: ${faults}`)
})

test('the log names logged by these checks are the ones on disk', () => {
  // A typo in the directory listing would make the whole file vacuous, so the set is pinned by name.
  assert.ok(logs.includes('probe-m3-restart.log'), `expected probe-m3-restart.log among ${logs.join(', ')}`)
  assert.ok(logs.includes('probe-coverage.log'))
  assert.ok(logs.every(name => basename(name) === name), 'the listing must be file names, not paths')
})
